version: "3.9"
services:
  pyflaskazureblob:
    build: .
    image: pyflaskazureblob:latest
    container_name: pyflaskazureblob
    environment:
      - AZURE_STORAGE_CONTAINER_NAME="yourContainerName"
      - AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=yourSA;AccountKey=yourkey;EndpointSuffix=core.windows.net")
    volumes: 
      - ./templates:/app/templates
    ports: 
      - "5000:5000"
    networks:
      - py-net
networks:
  py-net:
